---
# Deduplication Test Playbook
#
# This playbook is used for testing the metrics utility's deduplication feature.
#
# FACT CACHING FOR DEDUPLICATION TESTS:
# ======================================
# This playbook sets ansible_product_serial and ansible_machine_id as cacheable
# facts for deduplication testing. For this to work:
#
# 1. Job Template must have use_fact_cache=True (Enable Fact Storage)
# 2. Facts must be set with cacheable: yes parameter
# 3. AAP automatically persists these to main_host.ansible_facts on job completion
#
# This is the proper integration test approach - no direct DB manipulation needed.
# ================================

- hosts: all
  vars:
    play_gather: false  # Disable to prevent overwriting custom test variables
    extra_value: ""
  gather_facts: "{{ play_gather }}"
  tasks:
    - name: set a fact man
      set_fact:
        foo: "bar{{ extra_value }}"
        bar:
          a:
            b:
              - "c"
              - "d"
        cacheable: "{{ set_fact_cacheable | default(false) }}"
    - name: debug host variables for fact setting
      debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "ansible_product_serial variable defined: {{ ansible_product_serial is defined }}"
          - "ansible_product_serial value: {{ ansible_product_serial | default('NOT DEFINED') }}"
          - "ansible_machine_id variable defined: {{ ansible_machine_id is defined }}"
          - "ansible_machine_id value: {{ ansible_machine_id | default('NOT DEFINED') }}"
      when: ansible_product_serial is defined or ansible_machine_id is defined
    - name: Set ansible_product_serial as cacheable fact
      set_fact:
        ansible_product_serial: "{{ ansible_product_serial }}"
        cacheable: yes
      when: ansible_product_serial is defined

    - name: Set ansible_machine_id as cacheable fact
      set_fact:
        ansible_machine_id: "{{ ansible_machine_id }}"
        cacheable: yes
      when: ansible_machine_id is defined
    - name: debug facts after setting
      debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "ansible_product_serial fact set: {{ ansible_product_serial is defined }}"
          - "ansible_product_serial fact value: {{ ansible_product_serial | default('NOT SET') }}"
          - "ansible_machine_id fact set: {{ ansible_machine_id is defined }}"
          - "ansible_machine_id fact value: {{ ansible_machine_id | default('NOT SET') }}"
      when: ansible_product_serial is defined or ansible_machine_id is defined
